"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EVENT_TYPE = void 0;
var EVENT_TYPE;
(function (EVENT_TYPE) {
    EVENT_TYPE["CREATE_TEAM"] = "CREATE_TEAM";
    EVENT_TYPE["UPDATE_TEAM"] = "UPDATE_TEAM";
    EVENT_TYPE["DELETE_TEAM"] = "DELETE_TEAM";
    EVENT_TYPE["CREATE_TENTATIVE_QUEUE"] = "CREATE_TENTATIVE_QUEUE";
    EVENT_TYPE["UPDATE_TENTATIVE_QUEUE"] = "UPDATE_TENTATIVE_QUEUE";
    EVENT_TYPE["DELETE_TENTATIVE_QUEUE"] = "DELETE_TENTATIVE_QUEUE";
})(EVENT_TYPE = exports.EVENT_TYPE || (exports.EVENT_TYPE = {}));
;
